services:
  redis:
    image: redis:7-alpine
    container_name: kantares-redis
    environment:
      - TZ=America/Mexico_City
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - sh
      - -c
      - |
        exec redis-server --appendonly yes --requirepass "$${REDIS_PASSWORD}"
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a "$${REDIS_PASSWORD}" PING']
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
