/* eslint-disable @typescript-eslint/no-misused-promises */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedProductos() {
  console.log('🌱 Creando productos...');

  const productos = [
    // BEBIDAS FRÍAS (categoría 1)
    {
      sku: 'BEB-001',
      nombre: 'Coca Cola 355ml',
      descripcion: 'Refresco de cola',
      id_categoria: 1,
      id_unidad_medida: 1, // Pieza
      precio_venta: 35.0,
      costo_promedio: 18.0,
      tiempo_preparacion_min: 2,
      es_inventariable: true,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-002',
      nombre: 'Agua Natural 600ml',
      descripcion: 'Agua purificada embotellada',
      id_categoria: 1,
      id_unidad_medida: 1,
      precio_venta: 25.0,
      costo_promedio: 10.0,
      tiempo_preparacion_min: 2,
      es_inventariable: true,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-003',
      nombre: 'Limonada Natural',
      descripcion: 'Limonada preparada al momento',
      id_categoria: 1,
      id_unidad_medida: 7, // Porción
      precio_venta: 45.0,
      costo_promedio: 15.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-004',
      nombre: 'Naranjada Natural',
      descripcion: 'Jugo de naranja fresco',
      id_categoria: 1,
      id_unidad_medida: 7,
      precio_venta: 50.0,
      costo_promedio: 20.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // BEBIDAS CALIENTES (categoría 2)
    {
      sku: 'BEB-010',
      nombre: 'Café Americano',
      descripcion: 'Café espresso con agua caliente',
      id_categoria: 2,
      id_unidad_medida: 7,
      precio_venta: 40.0,
      costo_promedio: 12.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-011',
      nombre: 'Cappuccino',
      descripcion: 'Café espresso con leche espumada',
      id_categoria: 2,
      id_unidad_medida: 7,
      precio_venta: 55.0,
      costo_promedio: 18.0,
      tiempo_preparacion_min: 7,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-012',
      nombre: 'Té Verde',
      descripcion: 'Té verde natural',
      id_categoria: 2,
      id_unidad_medida: 7,
      precio_venta: 35.0,
      costo_promedio: 10.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // CERVEZAS (categoría 3)
    {
      sku: 'BEB-020',
      nombre: 'Corona 355ml',
      descripcion: 'Cerveza clara mexicana',
      id_categoria: 3,
      id_unidad_medida: 1,
      precio_venta: 50.0,
      costo_promedio: 25.0,
      tiempo_preparacion_min: 2,
      es_inventariable: true,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-021',
      nombre: 'Modelo Especial 355ml',
      descripcion: 'Cerveza tipo pilsner',
      id_categoria: 3,
      id_unidad_medida: 1,
      precio_venta: 45.0,
      costo_promedio: 22.0,
      tiempo_preparacion_min: 2,
      es_inventariable: true,
      es_vendible: true,
      disponible: true,
    },

    // COCTELES (categoría 5)
    {
      sku: 'BEB-030',
      nombre: 'Margarita',
      descripcion: 'Tequila, triple sec y limón',
      id_categoria: 5,
      id_unidad_medida: 7,
      precio_venta: 120.0,
      costo_promedio: 40.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'BEB-031',
      nombre: 'Piña Colada',
      descripcion: 'Ron, crema de coco y piña',
      id_categoria: 5,
      id_unidad_medida: 7,
      precio_venta: 130.0,
      costo_promedio: 45.0,
      tiempo_preparacion_min: 5,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // DESAYUNOS (categoría 6)
    {
      sku: 'ALI-001',
      nombre: 'Huevos Rancheros',
      descripcion: 'Huevos estrellados con salsa ranchera',
      id_categoria: 6,
      id_unidad_medida: 7,
      precio_venta: 95.0,
      costo_promedio: 35.0,
      tiempo_preparacion_min: 15,
      calorias: 450,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-002',
      nombre: 'Chilaquiles Verdes',
      descripcion: 'Totopos bañados en salsa verde',
      id_categoria: 6,
      id_unidad_medida: 7,
      precio_venta: 110.0,
      costo_promedio: 40.0,
      tiempo_preparacion_min: 15,
      calorias: 520,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-003',
      nombre: 'Hot Cakes',
      descripcion: 'Hot cakes con miel de maple',
      id_categoria: 6,
      id_unidad_medida: 7,
      precio_venta: 85.0,
      costo_promedio: 30.0,
      tiempo_preparacion_min: 12,
      calorias: 380,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // ENSALADAS (categoría 7)
    {
      sku: 'ALI-010',
      nombre: 'Ensalada César',
      descripcion: 'Lechuga romana, crutones, queso parmesano',
      id_categoria: 7,
      id_unidad_medida: 7,
      precio_venta: 120.0,
      costo_promedio: 45.0,
      tiempo_preparacion_min: 10,
      calorias: 320,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-011',
      nombre: 'Ensalada Griega',
      descripcion: 'Pepino, tomate, cebolla, aceitunas y queso feta',
      id_categoria: 7,
      id_unidad_medida: 7,
      precio_venta: 115.0,
      costo_promedio: 40.0,
      tiempo_preparacion_min: 10,
      calorias: 280,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // SOPAS (categoría 8)
    {
      sku: 'ALI-020',
      nombre: 'Sopa de Tortilla',
      descripcion: 'Caldo de jitomate con tiras de tortilla',
      id_categoria: 8,
      id_unidad_medida: 7,
      precio_venta: 80.0,
      costo_promedio: 30.0,
      tiempo_preparacion_min: 12,
      calorias: 250,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // CARNES (categoría 9)
    {
      sku: 'ALI-030',
      nombre: 'Arrachera a la Parrilla',
      descripcion: 'Arrachera marinada 300g',
      id_categoria: 9,
      id_unidad_medida: 7,
      precio_venta: 285.0,
      costo_promedio: 120.0,
      tiempo_preparacion_min: 25,
      calorias: 650,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-031',
      nombre: 'Rib Eye 400g',
      descripcion: 'Corte de res premium',
      id_categoria: 9,
      id_unidad_medida: 7,
      precio_venta: 380.0,
      costo_promedio: 180.0,
      tiempo_preparacion_min: 30,
      calorias: 780,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // AVES (categoría 10)
    {
      sku: 'ALI-040',
      nombre: 'Pechuga a la Plancha',
      descripcion: 'Pechuga de pollo marinada',
      id_categoria: 10,
      id_unidad_medida: 7,
      precio_venta: 165.0,
      costo_promedio: 60.0,
      tiempo_preparacion_min: 20,
      calorias: 420,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-041',
      nombre: 'Alitas BBQ',
      descripcion: '10 alitas con salsa BBQ',
      id_categoria: 10,
      id_unidad_medida: 7,
      precio_venta: 145.0,
      costo_promedio: 55.0,
      tiempo_preparacion_min: 20,
      calorias: 580,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // PASTAS (categoría 12)
    {
      sku: 'ALI-050',
      nombre: 'Spaguetti Carbonara',
      descripcion: 'Pasta con tocino y crema',
      id_categoria: 12,
      id_unidad_medida: 7,
      precio_venta: 155.0,
      costo_promedio: 50.0,
      tiempo_preparacion_min: 18,
      calorias: 620,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-051',
      nombre: 'Lasagna Boloñesa',
      descripcion: 'Lasagna con carne molida',
      id_categoria: 12,
      id_unidad_medida: 7,
      precio_venta: 175.0,
      costo_promedio: 60.0,
      tiempo_preparacion_min: 25,
      calorias: 680,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // HAMBURGUESAS (categoría 14)
    {
      sku: 'ALI-060',
      nombre: 'Hamburguesa Clásica',
      descripcion: 'Carne 180g, lechuga, tomate, cebolla',
      id_categoria: 14,
      id_unidad_medida: 7,
      precio_venta: 135.0,
      costo_promedio: 50.0,
      tiempo_preparacion_min: 15,
      calorias: 550,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'ALI-061',
      nombre: 'Hamburguesa BBQ Bacon',
      descripcion: 'Carne 180g, tocino, queso cheddar, BBQ',
      id_categoria: 14,
      id_unidad_medida: 7,
      precio_venta: 165.0,
      costo_promedio: 65.0,
      tiempo_preparacion_min: 15,
      calorias: 720,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },

    // POSTRES (categoría 17)
    {
      sku: 'POS-001',
      nombre: 'Helado de Vainilla',
      descripcion: '3 bolas de helado',
      id_categoria: 17,
      id_unidad_medida: 7,
      precio_venta: 65.0,
      costo_promedio: 25.0,
      tiempo_preparacion_min: 3,
      calorias: 320,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'POS-002',
      nombre: 'Flan Napolitano',
      descripcion: 'Flan casero con caramelo',
      id_categoria: 18,
      id_unidad_medida: 7,
      precio_venta: 70.0,
      costo_promedio: 28.0,
      tiempo_preparacion_min: 5,
      calorias: 280,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
    {
      sku: 'POS-003',
      nombre: 'Pastel de Chocolate',
      descripcion: 'Rebanada de pastel de chocolate',
      id_categoria: 18,
      id_unidad_medida: 7,
      precio_venta: 85.0,
      costo_promedio: 32.0,
      tiempo_preparacion_min: 5,
      calorias: 420,
      es_inventariable: false,
      es_vendible: true,
      disponible: true,
    },
  ];

  for (const producto of productos) {
    await prisma.productos.upsert({
      where: { sku: producto.sku },
      update: {},
      create: producto,
    });
  }

  console.log('✅ Productos creados exitosamente');
}

seedProductos()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
