/* eslint-disable @typescript-eslint/no-misused-promises */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedProveedores() {
  console.log('🌱 Creando proveedores...');

  const proveedores = [
    {
      razon_social: 'Abarrotes y Distribuidora del Centro SA de CV',
      nombre_comercial: 'Abarrotes del Centro',
      rfc: 'ADC890123AB1',
      direccion: 'Av. Constituyentes 234, Centro',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76000',
      telefono: '4421111111',
      email: 'ventas@abarrotescentro.com',
      contacto_nombre: 'José Luis Pérez',
      contacto_telefono: '4421111112',
      dias_credito: 15,
      limite_credito: 50000.0,
      cuenta_bancaria: '1234567890',
      banco: 'BBVA',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Carnes Finas del Bajío SA de CV',
      nombre_comercial: 'Carnes Premium',
      rfc: 'CFB910223CD2',
      direccion: 'Blvd. Bernardo Quintana 456',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76090',
      telefono: '4422222222',
      email: 'pedidos@carnesfinas.com',
      contacto_nombre: 'Roberto Martínez',
      contacto_telefono: '4422222223',
      dias_credito: 7,
      limite_credito: 80000.0,
      cuenta_bancaria: '0987654321',
      banco: 'Banorte',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Bebidas y Refrescos del Norte SA',
      nombre_comercial: 'Distribuidora de Bebidas',
      rfc: 'BRN920334EF3',
      direccion: 'Carretera México 57 Km 12',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76120',
      telefono: '4423333333',
      email: 'distribucion@bebidasnorte.com',
      contacto_nombre: 'María González',
      contacto_telefono: '4423333334',
      dias_credito: 30,
      limite_credito: 100000.0,
      cuenta_bancaria: '5555666777',
      banco: 'Santander',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Productos Lácteos La Vaquita SA de CV',
      nombre_comercial: 'Lácteos La Vaquita',
      rfc: 'PLV930445GH4',
      direccion: 'Av. 5 de Febrero 789',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76030',
      telefono: '4424444444',
      email: 'ventas@lavaquita.com',
      contacto_nombre: 'Carmen Sánchez',
      contacto_telefono: '4424444445',
      dias_credito: 10,
      limite_credito: 40000.0,
      cuenta_bancaria: '8888999000',
      banco: 'HSBC',
      calificacion: 4,
      activo: true,
    },
    {
      razon_social: 'Frutas y Verduras Frescas del Campo SA',
      nombre_comercial: 'Frescura del Campo',
      rfc: 'FVF940556IJ5',
      direccion: 'Central de Abastos Local 45',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76140',
      telefono: '4425555555',
      email: 'pedidos@frescuradelcampo.com',
      contacto_nombre: 'Luis Hernández',
      contacto_telefono: '4425555556',
      dias_credito: 3,
      limite_credito: 25000.0,
      cuenta_bancaria: '1111222333',
      banco: 'Scotiabank',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Vinos y Licores Selectos SA de CV',
      nombre_comercial: 'Licores Premium',
      rfc: 'VLS950667KL6',
      direccion: 'Av. Universidad 321',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76010',
      telefono: '4426666666',
      email: 'ventas@licoreselectos.com',
      contacto_nombre: 'Patricia Torres',
      contacto_telefono: '4426666667',
      dias_credito: 15,
      limite_credito: 60000.0,
      cuenta_bancaria: '4444555666',
      banco: 'Banamex',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Panadería y Repostería Artesanal SA',
      nombre_comercial: 'Pan Artesanal',
      rfc: 'PRA960778MN7',
      direccion: 'Calle Morelos 567',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76000',
      telefono: '4427777777',
      email: 'pedidos@panartesanal.com',
      contacto_nombre: 'Fernando Ramírez',
      contacto_telefono: '4427777778',
      dias_credito: 5,
      limite_credito: 15000.0,
      cuenta_bancaria: '7777888999',
      banco: 'Banregio',
      calificacion: 4,
      activo: true,
    },
    {
      razon_social: 'Mariscos y Pescados del Pacífico SA',
      nombre_comercial: 'Mariscos Frescos',
      rfc: 'MPP970889OP8',
      direccion: 'Mercado de Mariscos Local 12',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76050',
      telefono: '4428888888',
      email: 'ventas@mariscospacifico.com',
      contacto_nombre: 'Rodrigo Díaz',
      contacto_telefono: '4428888889',
      dias_credito: 2,
      limite_credito: 35000.0,
      cuenta_bancaria: '2222333444',
      banco: 'Inbursa',
      calificacion: 4,
      activo: true,
    },
    {
      razon_social: 'Insumos para Restaurante Pro SA de CV',
      nombre_comercial: 'Restaurant Pro',
      rfc: 'IRP980990QR9',
      direccion: 'Parque Industrial Querétaro',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76220',
      telefono: '4429999999',
      email: 'ventas@restaurantpro.com',
      contacto_nombre: 'Gabriela Morales',
      contacto_telefono: '4429999990',
      dias_credito: 30,
      limite_credito: 45000.0,
      cuenta_bancaria: '6666777888',
      banco: 'Afirme',
      calificacion: 5,
      activo: true,
    },
    {
      razon_social: 'Café Gourmet de Altura SA',
      nombre_comercial: 'Café Premium',
      rfc: 'CGA991001ST0',
      direccion: 'Av. Zaragoza 890',
      ciudad: 'Querétaro',
      estado: 'Querétaro',
      codigo_postal: '76020',
      telefono: '4420000000',
      email: 'pedidos@cafepremium.com',
      contacto_nombre: 'Alberto Jiménez',
      contacto_telefono: '4420000001',
      dias_credito: 20,
      limite_credito: 30000.0,
      cuenta_bancaria: '9999000111',
      banco: 'Banorte',
      calificacion: 5,
      activo: true,
    },
  ];

  for (const proveedor of proveedores) {
    await prisma.proveedores.upsert({
      where: { rfc: proveedor.rfc },
      update: {},
      create: proveedor,
    });
  }

  console.log('✅ Proveedores creados exitosamente');
}

seedProveedores()
  .catch((e) => {
    console.error('❌ Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
